### ISSUE TITLE
Could you check the calculations for the memory

### ISSUE THREAD

**Issue by arcolinuxz** [blmayer/sysmon#5]
![check mem](https://github.com/blmayer/sysmon/assets/36679406/6e6b5ec3-3952-4b4e-a2a9-5ea2cfd431b9)

I see different memory usage on xfce4 task manager and btop and sysmon.

Maybe there is something different on Arch or something was updated.

**Comment by blmayer** [comment]
Hi, thanks for opening up this issue.

Sysmon only considers free memory, that's unused memory. I think other monitors may consider caches or uncommitted memory as free, that's why they show different results. 

My idea to consider this was simplicity. But I see no problem in changing the math here in order to get consistent results. 

I confess my understanding of what "free memory" means is of a layman, since Linux has many types of memory. So I used the free memory value that meminfo called free.

**Comment by blmayer** [comment]
Thanks @arcolinuxz for bringing this up. The release v1.1.3 fixed this.
